<a href="https://colab.research.google.com/github/nedokormysh/GB_Linear_Algebra/blob/lesson4/Linear_Algebra_HW_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from numpy import linalg as la
import scipy
import scipy.linalg

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$


$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2  \\ 
2 & 1 & -1 & 1 \\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Вычтем из второй строки удвоенную первую строку. И из третьей вычтем первую.

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2  \\ 
0 & -1 & 1 & 5 \\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$


$$\begin{cases}
x_{1} + x_2 - x_3 - 2x_{4} = 0 \\
-x_{2} + x_{3} + 5x_{4} = -2 \\
-2x_3 + 3x_4 = 4
\end{cases}$$

Система имеет бесконечное множество решений

$$x_4 = c$$
$$x_3 = \frac{3c - 4}{2}$$
$$x_2 = \frac{3c - 4}{2} + 5 c +2 = \frac{13}{2}c$$
$$x_1 = - \frac{13}{2}c + \frac{3c - 4}{2} + 2 c = -3 c - 2$$

$$\begin{cases}
x_1 = -3 c - 2 \\
x_2 = \frac{13}{2}c \\
x_3 = \frac{3c - 4}{2} \\
x_4 = c
\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

Матрица коэффициентов А$${A}=\begin{pmatrix}
3 & -1 & 1 \\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{pmatrix}.$$

Нет линейно зависимых строк. Следовательно ранг матрицы = 3.

Расширенная матрица:$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}.$$

Ранг расширенной матрицы также равен 3.

$$rank A = rank \tilde A = 3.$$ 

Система определена. Имеет единственное решение.


In [5]:
def K_K(A, A_t):  
  if (la.matrix_rank(A) == la.matrix_rank(A_t) and la.matrix_rank(A_t) == np.shape(A)[1]):
    return 'Система совместна, определена. Имеет единственное решение.'
  elif (la.matrix_rank(A) == la.matrix_rank(A_t) and la.matrix_rank(A_t) < np.shape(A)[1]):
    return 'Система совместна. Имеет бесконечное количество решений'
  elif(la.matrix_rank(A) < la.matrix_rank(A_t)):
    return 'Система несовместна'

In [6]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A_t = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])

# print(f'Ранг А = {la.matrix_rank(A), la.matrix_rank(A_t)}')
print(K_K(A, A_t))

Система совместна, определена. Имеет единственное решение.


б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

Матрица коэффициентов А$${A}=\begin{pmatrix}
2 & -4 & 6 \\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{pmatrix}.$$

Ранг матрицы коэффициентов равен 1, т.к. первая и вторая, и вторая и третья строки линейно зависимы.

Расширенная матрица:$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}.$$

Ранг расширенной матрицы равен 3, т.к. нет линейно зависимых строк.

$$rankA<rank \tilde A$$ Система несовместна.

In [7]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A_t = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])

print(K_K(A, A_t))

Система несовместна


в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

Матрица коэффициентов А$${A}=\begin{pmatrix}
1 & 2 & 5 \\ 
3 & 1 & -8
\end{pmatrix}.$$

Нет линейно зависимых строк. Ранг матрицы равен 2.

Расширенная матрица:$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\ 
-2\\
\end{matrix}
\end{pmatrix}.$$

Ранг расширенной матрицы равен 2.

Количество неизвестных $=3 >$ число уравнений. 

$rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>

In [8]:
A = np.array([[1, 2, 5], [3, 1, -8]])
A_t = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])

print(K_K(A, A_t))

Система совместна. Имеет бесконечное количество решений


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Ранг матрицы коэффициентов равен рангу расширенной матрицы = 4. Количество неизвестных = 4. Таким образом система совместна и имеет одно единственное решение.

In [9]:
A = np.array([[1, 3, 2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([[3], [2], [4], [1]])
A_t = np.hstack((A, b))

# print(A_t)

print(K_K(A, A_t))

Система совместна, определена. Имеет единственное решение.


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} =
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 7a
\end{matrix}
\end{pmatrix} =
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 2b + a
\end{matrix}
\end{pmatrix}$$

Ранг матрицы коэффициентов = 2. Для несовместности системы требуется, чтобы ранг расширенной матрицы был больше, чем ранг матрицы коэффициентов. Из этого следует, что при c - 2b + a $\neq$ 0 наша система будет несовместной.


In [10]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'Ранг А = {la.matrix_rank(A)}')

Ранг А = 2


# Системы линейных уравнений. Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
$$detA = \begin{vmatrix}
1 & -2\\ 
3 & -4\\ 
\end{vmatrix} = -4 + 6 = 2  \neq 0$$

Cистема совместна.

$$detA_1 = \begin{vmatrix}
1 & -2\\ 
7 & -4\\ 
\end{vmatrix} = -4 + 14 = 10$$

$$$$
$$detA_2 = \begin{vmatrix}
1 & 1\\ 
3 & 7\\ 
\end{vmatrix} = 7 - 3 = 4$$

$$$$
$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2} = 5$$
<br>
$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2} = 2$$

In [ ]:
A = np.array([[1,-2],[3,-4]])
A1 = np.array([[1, -2],[7, -4]])
A2 = np.array([[1, 1],[3, 7]])

detA = la.det(A)
detA_1 = la.det(A1)
detA_2 = la.det(A2)

x_1 = round(detA_1 / detA, 1)
x_2 = round(detA_2 / detA, 1)

print(f'x_1 = {x_1}, x_2 = {x_2}')

x_1 = 5.0, x_2 = 2.0


In [ ]:
# a = np.array([[1, -2],[3, -4]])
# b = np.array([1, 7])

# np.linalg.solve(a,b)

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix} = 2 \cdot 1 \cdot 1 + (-1) \cdot (-3) \cdot 2 + 5 \cdot 1 \cdot 4 - 2 \cdot 1 \cdot 5 - 4 \cdot (-3) \cdot 2 - 1 \cdot 1 \cdot(-1) = 28 + 15  = 43  \neq 0,$$

Система совместна.

$$detA_1 = \begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix} = 10 \cdot 1 \cdot 1 + (-1) \cdot (-3) \cdot 1 + 5 \cdot (-2) \cdot 4 - 1 \cdot 1 \cdot 5 - 4 \cdot (-3) \cdot 10 - 1 \cdot (-2) \cdot (-1) = 28 + 15  =  86$$
$$$$
$$x_1 = 2$$

$$detA_2 = \begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix} = 2 \cdot (-2) \cdot 1 + 10 \cdot (-3) \cdot 2 + 5 \cdot 1 \cdot 1 - 2 \cdot (-2) \cdot 5 - 1 \cdot (-3) \cdot 2 - 1 \cdot 1 \cdot 10 = -43 $$

$$$$
$$x_2 = -1$$
$$$$

$$detA_3 = \begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix} = 2 \cdot 1 \cdot 1 + (-1) \cdot (-2) \cdot 2 + 10 \cdot 1 \cdot 4 - 2 \cdot 1 \cdot 10 - 4 \cdot (-2) \cdot 2 - 1 \cdot 1 \cdot (-1) =  43$$
$$$$
$$x_3 = 1$$

In [11]:
A = np.array([[2, 1, 2], [-1, 1, 4], [5, -3, 1]])
A1 = np.array([[10, -2, 1], [-1, 1, 4], [5, -3, 1]])
A2 = np.array([[2, 1, 2], [10, -2, 1], [5, -3, 1]])
A3 = np.array([[2, 1, 2], [-1, 1, 4], [10, -2, 1]])
# B = [10, -2, 1]
# A3 = np.hstack(((np.delete(A, np.s_[2:], 1)), (np.delete(A, np.s_[:3],1))))
# A3 = np.hstack((A3, B))

detA = la.det(A)
detA_1 = la.det(A1)
detA_2 = la.det(A2)
detA_3 = la.det(A3)

x_1 = round(detA_1 / detA, 1)
x_2 = round(detA_2 / detA, 1)
x_3 = round(detA_3 / detA, 1)

print(f'x_1 = {x_1}, x_2 = {x_2}, x_3 = {x_3}')

x_1 = 2.0, x_2 = -1.0, x_3 = 1.0


In [ ]:
# a = np.array([[2, -1, 5],[1, 1,-3],[2, 4, 1]])
# b = np.array([10, -2, 1])

# np.linalg.solve(a,b)

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix} = U$$
    

$$L =\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$
  

In [13]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])

print(f'L = \n{LU_solver.LU_generator(A)[0]}')
print(f'U = \n{LU_solver.LU_generator(A)[1]}')

L = 
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 4. 1.]]
U = 
[[1. 2. 4.]
 [0. 5. 4.]
 [0. 0. 2.]]


 б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix} = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
4 & 18 & 45 & 17
\end{pmatrix} = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix} = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix} = U$$$$L = \begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}$$

In [14]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
      
print(f'L = \n{LU_solver.LU_generator(A)[0]}')
print(f'U = \n{LU_solver.LU_generator(A)[1]}')

L = 
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [3. 5. 1. 0.]
 [4. 6. 7. 1.]]
U = 
[[1. 1. 2. 4.]
 [0. 3. 4. 1.]
 [0. 0. 3. 1.]
 [0. 0. 0. 4.]]


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Найдём L.

$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix} $

$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 3.5 & -9.5
\end{pmatrix}  $

$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}  $

$L =  \begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix} = \begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & l_{32} & 1
\end{pmatrix} =
\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}$



$Ly = b$

$$\begin{cases}
y_{1}=1 \\
\frac{11}{2}y_1 + y_2  =-6 \\
\frac{9}{2}y_1 +\frac{7}{3}y_2 + y_3=-5
\end{cases} \Rightarrow 
\begin{cases}
y_{1}=1 \\
y_2  =-\frac{23}{2} \\
y_3=\frac{52}{3}
\end{cases}$$

$Ux = y$

$$\begin{cases}
2x_1 + x_2 + 3x_3=1 \\
 \frac{3}{2}x_2 -\frac{23}{2}x_3  =-\frac{23}{2} \\
\frac{52}{3}x_3=\frac{52}{3}
\end{cases} \Rightarrow
\begin{cases}
x_1 = -1 \\
x_2 = 0 \\
x_3=1
\end{cases}
$$


In [15]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
B = np.array([1, -6, -5])
print(f'x = {LU_solver.solve(A, B)}')

x = [-1. -0.  1.]


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11} = \sqrt{a_{11}} = \sqrt{81} = 9$$
$$l_{21} = \frac{a_{21}}{l_{11}} = -\frac{45}{9} = -5$$
$$l_{31} = \frac{a_{31}}{l_{11}} = \frac{45}{9} = 5$$

$$l_{22} = \sqrt{a_{22}-l_{21}^{2}} = \sqrt{50 - 25} = 5$$
$$l_{32} = \frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right) = \frac{1}{5}\left ( -15 - (-5)\cdot 5 \right ) = 2$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}} = \sqrt{38 - 25 - 4} = 3.$$


Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1} = 531 \\
-5y_{1} + 5y_{2} = -460 \\
5y_{1} + 2y_{2} + 4y_{3} = 193.
\end{cases}$$

$$y_{1} = 59$$

$$y_{2} = - 33$$

$$y_{3} = -12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1} - 5x_{2} + 5x_{3} = 59 \\
5x_{2} + 2x_{3} = -33 \\
3x_{3} = -12.
\end{cases}$$

$$x_{3} = -4$$

$$x_{2} = -5$$

$$x_{1} = 6$$

In [16]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
B = np.array([531, -460, 193])
print(f'x = {LU_solver.solve(A, B)}')

x = [ 6. -5. -4.]


__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [12]:
class LU_solver:
  
  def L_filler(self, L):
    U = self
    p = 0
    for c in range(0, np.shape(L)[1]):
      p += 1
      for i in range(p, np.shape(L)[0]):
        U = U.astype(float)
        L[i][c] = U[i][c] / U[c][c]
        U[i] = U[i] - L[i][c] * U[c]
    return L, U

  def LU_generator(self):
    L = np.tri(np.shape(self)[0])
    LU_solver.L_filler(self, L)
    L = LU_solver.L_filler(self, L)[0]
    U = LU_solver.L_filler(self, L)[1]
    return L, U

  def solve(self, B):
    L, U = LU_solver.LU_generator(self)[0], LU_solver.LU_generator(self)[1]

    y = np.array([1] * len(L), float)

    y = np.linalg.inv(L).dot(B)
    x = np.linalg.inv(U).dot(y)

    x = np.round(x, 2)
    return x