<a href="https://colab.research.google.com/github/nedokormysh/GB_Linear_Algebra/blob/lesson5/Linear_Algebra_HW_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$



In [ ]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(f'A = \n{A}')

U, s, W = np.linalg.svd(A)

V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'U = \n{U} \n D = \n{D} \n V = \n{W.T}')

A = 
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
U = 
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]] 
 D = 
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]] 
 V = 
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [ ]:
print(np.dot(U.T, U))

[[ 1.  0. -0. -0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0. -0.]
 [-0.  0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]


In [ ]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [ ]:
# Euklides

print(f'Норма eвклидова норма numpy = {np.linalg.norm(A, ord=2)}')
print(f'Норма eвклидова норма как первый элемент диагональной матрицы = {s[0]}')

Норма eвклидова норма numpy = 8.824868854820444
Норма eвклидова норма как первый элемент диагональной матрицы = 8.824868854820442


In [ ]:
# Frobenius

summ = 0
for i in range(0, np.shape(A)[0]):
  for j in range(0, np.shape(A)[1]):
    summ += A[i][j]**2

frob1 = np.sqrt(summ)

frob2 = np.sqrt(np.sum([(el**2) for el in s]))

print(f'Норма Фробениуса numpy = {np.linalg.norm(A, ord="fro")}')
print(f'Норма Фробениуса корень из суммы квадратов всех элеметов матрицы А = {frob1}\nНорма Фробениуса как корень из суммы квадтратов диагональной элементов диагональной матрицы. = {frob2}')

Норма Фробениуса numpy = 11.045361017187261
Норма Фробениуса корень из суммы квадратов всех элеметов матрицы А = 11.045361017187261
Норма Фробениуса как корень из суммы квадтратов диагональной элементов диагональной матрицы. = 11.045361017187261
