<a href="https://colab.research.google.com/github/nedokormysh/GB_Linear_Algebra/blob/lesson2/Linear_Algebra_HW_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import math

__1.__ *Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:*

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


**Решение. **  
а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;<br>
m строк n столбцов. Для перемножения требуется, чтобы количество столбцов у матрицы А совпадало с количеством столбцов у матрицы B. В данном случае это не так. Следовательно произведение матриц AB и BA в данном случае не определено.

In [17]:
A = np.empty((4, 2))
B = np.empty((4, 2))

# # print(np.shape(A)[1])
# # print(np.shape(B)[0])

print('Умножение AB возможно') if np.shape(A)[1] == np.shape(B)[0] else print('Умножение AB невозможно')
print('Умножение BA возможно') if np.shape(B)[1] == np.shape(A)[0] else print('Умножение BA невозможно')

Умножение AB невозможно
Умножение BA невозможно


б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;<br>

Умножение $A$  на $B$ возможно. Должны получить матрицу $2\times 3$. 

Умножение $B$  на $A$ невозможно.

In [18]:
A = np.empty((2, 5))
B = np.empty((5, 3))

print('Умножение AB возможно') if np.shape(A)[1] == np.shape(B)[0] else print('Умножение AB невозможно')
print('Умножение BA возможно') if np.shape(B)[1] == np.shape(A)[0] else print('Умножение BA невозможно')

C = np.dot(A, B)
print(C.shape)

Умножение AB возможно
Умножение BA невозможно
(2, 3)


в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

Возможны оба варианта перемножения.

$A \cdot B$ даст матрицу $8 \times 8$<br>
$B \cdot A$ даст матрицу $3 \times 3$


In [19]:
A = np.empty((8, 3))
B = np.empty((3, 8))

print('Умножение AB возможно') if np.shape(A)[1] == np.shape(B)[0] else print('Умножение AB невозможно')
C = np.dot(A, B)
print(C.shape)

print('Умножение BA возможно') if np.shape(B)[1] == np.shape(A)[0] else print('Умножение BA невозможно')

C = np.dot(B, A)
print(C.shape)

Умножение AB возможно
(8, 8)
Умножение BA возможно
(3, 3)


г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Возможны оба варианта перемножения.

$A \cdot B$ даст матрицу $4 \times 4$<br>
$B \cdot A$ даст матрицу $4 \times 4$

In [20]:
A = np.empty((4, 4))
B = np.empty((4, 4))

print('Умножение AB возможно') if np.shape(A)[1] == np.shape(B)[0] else print('Умножение невозможно')
C = np.dot(A, B)
print(C.shape)

print('Умножение BA возможно') if np.shape(B)[1] == np.shape(A)[0] else print('Умножение невозможно')

C = np.dot(B, A)
print(C.shape)

Умножение AB возможно
(4, 4)
Умножение BA возможно
(4, 4)


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

<br>

$A + B = \begin  {pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}. = \begin{pmatrix}
1 + 4 & -2 -1\\ 
3 + 0 & 5 + 0
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

<br>

$A*B = \begin  {pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ * $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 \cdot 4 -2\cdot0 & 1\cdot(-1) + (-2)\cdot5\\ 
3\cdot4 + 0\cdot0 & 3\cdot(-1) + 0\cdot5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

<br>

$B*A = \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ * $ \begin  {pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
4 \cdot 1 -1 \cdot 3 & 4 \cdot(-2) + (-1) \cdot 0\\ 
0 \cdot 1 + 5 \cdot 3 & 0 \cdot (-2) + 5 \cdot 0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [21]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Сумма A + B = \n{A + B}\n')
print(f'A * B = \n{np.dot(A, B)}\n')
print(f'B * A = \n{np.dot(B, A)}')

Сумма A + B = 
[[ 5 -3]
 [ 3  5]]

A * B = 
[[  4 -11]
 [ 12  -3]]

B * A = 
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$   

<br>

$3 * A=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$

$2 * B=\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$

$4 * C=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$

<br>

$3 * A - 2 * B=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} = \begin{pmatrix}
3 & 11\\ 
5 & -16
\end{pmatrix}$

<br>
$3A - 2B + 4C = \begin{pmatrix}
3 & 11\\ 
5 & -16
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$


In [15]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(3 * A - 2 * B + 4 * C)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


$A^{T} = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

<br>

$AA^{T} = A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3\\ 
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) & 5 \cdot 2 + (-2) \cdot 3\\ 
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13\end{pmatrix}$

<br>

$A^{T}A = 
\begin{pmatrix}
  4 & 5 & 2\\ 
  1 & -2 & 3
\end{pmatrix} \cdot 
\begin{pmatrix}
  4 & 1\\ 
  5 & -2\\ 
  2 & 3
\end{pmatrix} = \begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3\\ 
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3\\ 
\end{pmatrix} = 
\begin{pmatrix}
  45 & 0 \\ 
  0 & 14 \\
\end{pmatrix}$

In [6]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'A*A.T = \n{np.dot(A, A.T)}\n')
print(f'A.T*A = \n{np.dot(A.T, A)}')

A*A.T = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A.T*A = 
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def dot_simple(A, B):
    try:
        if (np.shape(A)[1] != np.shape(B)[0]):
            raise ValueError('Error')
    except:
        return f'Умножение невозможно. Размерности должны быть заданы правильно: количество столбцов первой матрицы ({np.shape(A)[1]}) должно совпадать с количеством строк второй матрицы ({np.shape(B)[0]})'

    print(f'Умножение возможно. Должны получить матрицу размерности {np.shape(A)[0]} на {np.shape(B)[1]}')

    sum = 0
    matrix = []

    for i in range(0, np.shape(A)[0]):
        for j in range(0, np.shape(B)[1]):
            for p in range(0, np.shape(B)[0]):
                sum += A[i][p] * B[p][j]
            matrix.append(sum)
            sum = 0
    matrix = np.array(matrix)
    # print(matrix)
    matrix = matrix.reshape(np.shape(A)[0], np.shape(B)[1])
    return matrix

Тесты:

In [ ]:
x = np.array([[1, 0], [2, 1], [10, 5]])
y = np.array([[2, 0, 0], [0, 0, 1]])

print(dot_simple(x, y))

Умножение возможно. Должны получить матрицу размерности 3 на 3
[[ 2  0  0]
 [ 4  0  1]
 [20  0  5]]


In [ ]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(dot_simple(A, A.T))
print(dot_simple(A.T, A))

Умножение возможно. Должны получить матрицу размерности 3 на 3
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Умножение возможно. Должны получить матрицу размерности 2 на 2
[[45  0]
 [ 0 14]]


In [ ]:
A = np.empty((2, 5))
B = np.empty((5, 3))

print(dot_simple(A, B))
print(dot_simple(B, A))

Умножение возможно. Должны получить матрицу размерности 2 на 3
[[0. 0. 0.]
 [0. 0. 0.]]
Умножение невозможно. Размерности должны быть заданы правильно: количество столбцов первой матрицы (3) должно совпадать с количеством строк второй матрицы (2)


__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = \sin^2 x + \cos^2x =1$$

  


 б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180$$
  

  
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1
\begin{vmatrix}
 5 & 6\\ 
 8 & 9
\end{vmatrix} - 2
\begin{vmatrix}
 4 & 6\\ 
 7 & 9
\end{vmatrix} + 3
\begin{vmatrix}
 4 & 5\\ 
 7 & 8
\end{vmatrix} = (5\cdot 9 - 8 \cdot 6) - 2(4 \cdot 9 - 7 \cdot 6) + 3 (4\cdot 8 - 7 \cdot 5) =
\\= (45 - 48) - 2(36 - 42) + 3(32 - 35) = -3 + 12 - 9 = 0$

In [ ]:
x = 1
A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}\n')
print(f'Матрица:\n{B}')
print(f'Определитель:\n{np.linalg.det(B):.0f}\n')
print(f'Матрица:\n{C}')
print(f'Определитель:\n{np.linalg.det(C):.0f}\n')

Матрица:
[[ 0.84147098 -0.54030231]
 [ 0.54030231  0.84147098]]
Определитель:
1

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0



__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;

  $det(A^{2}) = det(A \cdot A) = det(A) \cdot det(A) = 4 \cdot 4 = 16$;
    
   б) $det(A^{T})$;

   $det(A^{T}) = detA = 4$;
    
   в) $det(2A) = 8$.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Определитель вырожденной матрицы равен нулю. Найдём определитель.

$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = (-2)\cdot(-14)\cdot13 + 7 \cdot 6 \cdot (-13) + (-3) \cdot 4 \cdot 7 - (-3) \cdot (-14) \cdot ( -3) - (-2) \cdot 6 \cdot 7 - 13 \cdot4 \cdot 7 = 364 - 126 - 84 + 126 + 84 + 364 = 0$$

Первая и вторая строка матрицы линейно зависимы, а потому определитель равен нулю. Матрица является вырожденной.

In [ ]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(A)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Третья строка является суммой первых двух. Её можно отбросить


$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix};$

Вычтем из первой строки вторую


$\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1
\end{pmatrix};$

Ранг матрицы равен 2.

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Третья строка является суммой первых двух. Её можно отбросить.

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Ранг матрицы равен 3.

In [ ]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

print(f'Ранг матрицы a: {np.linalg.matrix_rank(a)}')
print(f'Ранг матрицы b: {np.linalg.matrix_rank(b)}')

Ранг матрицы a: 2
Ранг матрицы b: 3
